[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://recipe-platform-api-2025-6a69309dbc66.herokuapp.com"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
