[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  REACT_APP_API_URL = "https://savora-recipe-b7493c60c573.herokuapp.com"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
